sudo: required
dist: trusty

before_script:
    - sudo apt-get install libreadline-dev libffi-dev
    - git clone --recurse-submodules https://github.com/micropython/micropython.git
    - cd micropython/unix
    - make axtls
    - make

script:
    - ./micropython --help
